config/routes.rb
Rails.application.routes.draw do
  resources :urls
  get 'urls/:id', to: 'urls#show_full'
  root 'urls#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:edit, :update, :destroy, :show_full]

def index
  @urls = Url.all
end

def show
  url = Url.where(:random_id=>params[:id]).first
  if url
    redirect_to url.name
  else
    redirect_to "index"
  end
end

def show_full
  redirect_to @url.name
end
#
# def show_name
#   redirect_to "http://#{@url.name}"
# end

def new
  @url = Url.new

  letters = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
  @url.random_id = (0..4).map{ letters[rand(letters.length)] }.join
end

def edit
end

def create
  @url = Url.new(url_params)

  respond_to do |format|
    if @url.save
      format.html { redirect_to urls_path, notice: 'Url was successfully created.' }
      format.json { render :show, status: :created, location: @url }
    else
      format.html { render :new }
      format.json { render json: @url.errors, status: :unprocessable_entity }
    end
  end
end

def update
  respond_to do |format|
    if @url.update(url_params)
      format.html { redirect_to @url, notice: 'Url was successfully updated.' }
      format.json { render :show, status: :ok, location: @url }
    else
      format.html { render :edit }
      format.json { render json: @url.errors, status: :unprocessable_entity }
    end
  end
end

def destroy
  @url.destroy
  respond_to do |format|
    format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
    format.json { head :no_content }
  end
end

private

  def set_url
    @url = Url.find(params[:id])
  end


  def url_params
    params.require(:url).permit(:name, :random_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShort2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with model: url do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :url_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', url_path %> 

app/views/urls/index.html.erb
<h1>Url Shortener</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= link_to url.random_id, url_path(:id => url.random_id) %> => <%= url.name %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= form_for @url do |f| %>
<p>
<%= f.label :name%> : <%= f.url_field :name %>
</p>
<p>
  <%= f.hidden_field :random_id, :value => @url.random_id %>
</p>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>
<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p>
  <strong>Name:</strong>
  <%= link_to @url.id, "show_full/#{@url.id}" %>

</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>